export function i18n(): any {
  return {
    en: {
      mainQuestiinHeader: "All Questions",
      askQuestion: "Ask a question",
      password: "Password",
      confirmPassword: "Confirm password",
      email: "Email address",
      signInWelcomeTitle: "Sign in to your account",
      signUpWelcomeTitle: "Create your account",
      passwordsDoNotMatch: "Passwords don't match",
      welcomeVariants: "Or continue with",
      haveNoAccount: "Don't have an account?",
      haveAccount: "Already have an account?",
      successSignIn: "User was signed in successfully!",
      successSignUp: "Account was created successfully",
      titleError:
        "Question with similar title has already been asked on our platform. Please search it on qustions page.",
      requiredMessage: "The field is required and cannot be empty",
      searchQuestions: "Search for questions",
      tinyPlaceholder: "Provide a description to your question (optional)",
      asked: "asked",
      ago: "ago",
      week: "week",
      weeks: "weeks",
      day: "day",
      days: "days",
      hour: "hour",
      hours: "hours",
      month: "month",
      months: "months",
      minute: "minute",
      minutes: "minutes",
      second: "second",
      seconds: "seconds",
      noAnswer: "No answers yet",
      answer: "answer",
      answers: "answers",
      answered: "answered",
      questions: "Questions",
      question: "Question",
      questions2: "Questions",
      questions3: "question",
      questions4: "questions",
      questions5: "questions",
      comments: "comments",
      comment1: "comment",
      page: "Page",
      from: "from",
      profile: "Profile",
      users: "Users",
      tags: "Tags",
      topQuestions: "Top Questions",
      topTags: "Popular Tags",
      login: "Sign in",
      signup: "Sign up",
      aboutUsPageTitle: "About us",
      aboutUsParagraph1:
        "Wanswers was created to be a place where people can freely ask questions and get helpful answers.",
      aboutUsParagraph2:
        "We think everyone has useful advice to share, and asking questions is key to learning. Whether you're interested in tech, health, education, or tips for everyday life, Wanswers is where people with knowledge in these areas share their insights.",
      aboutUsParagraph3:
        "Our community is friendly and always ready to share their knowledge and experiences. Whether you're a student, a professional, or just curious, Wanswers is the right place for you.",
      aboutUsParagraph4:
        "Our team consists of people from different professional backgrounds who share a love for learning and a desire to make a positive contribution to society. These backgrounds include education, technology, and communication.",
      aboutUsParagraph5:
        "We noticed that there was a need for a platform where people could ask questions and receive answers without fear of being judged. This is why we made and now run Wanswers - a website that helps you find the information you need and encourages everyone to share what they know.",
      aboutUsParagraph6:
        "What makes Wanswers unique is our attention to quality and cooperation. It's one of our key goals to make it possible for the users to dialogue with each other, not only via posting responses but also through leaving sincere and useful comments, as well as maintaining a constructive attitude. Our moderators work hard to ensure that our content is factual, helpful, and appropriate, making our website a safe place for learning.",
      aboutUsParagraph7:
        "We hope you enjoy exploring our platform and joining a community that loves learning and making connections. Whether you're seeking answers or sharing your expertise, your participation enriches our collective understanding.",
      aboutUsParagraph8: "If you have any suggestions or feedback, we are always here to listen.",
      termsPageTitle: "Terms and Conditions",
      termsTitle1: "1. User Accounts",
      termsTitle2: "2. User Conduct",
      termsTitle3: "3. Ownership of Content",
      termsTitle4: "4. Privacy and Data Handling",
      termsTitle5: "5. Disclaimers",
      termsTitle6: "6. Liability Limitation",
      termsTitle7: "7. Governing Law and Dispute Resolution",
      termsTitle8: "8. Changes to These Terms",
      termsParagraph0:
        "Welcome to Wanswers.com. By using our website, you agree to these terms and conditions. If you do not agree, please do not use the website. We reserve the right to update these terms at any time, and you are responsible for reviewing them periodically.",
      termsParagraph1:
        "To post questions or answers on Wanswers.com, you must create an account. You are responsible for maintaining the confidentiality of your account information and ensuring that your information is accurate.",
      termsParagraph2:
        "When using Wanswers.com, you agree to: <ul className='ml-8 list-disc'><li>Avoid spam, hate speech, harassment, or other inappropriate content.</li><li>Refrain from posting copyrighted material without permission.</li><li>Follow any additional rules or guidelines we may implement.</li></ul><p className='mt-5'>We reserve the right to moderate content, remove inappropriate content, and take action against users who violate these terms.</p>",
      termsParagraph3:
        "By posting questions or answers on Wanswers.com, you grant us ownership of the content. This allows us to display, distribute, and modify the content as needed. You retain no ownership rights over the content you post.",
      termsParagraph4:
        'We are committed to protecting your privacy. Wanswers.com collects and uses your data according to common privacy practices, including: <ul className="ml-8 list-disc"> <li>Collecting user data for site functionality and improvement.</li> <li>Not sharing your data with third parties, except as required by law.</li> <li>Storing user data securely to prevent unauthorized access.</li> </ul> <p className="mt-5"> For more details, refer to our <a href="/privacy-policy">Privacy Policy</a>. </p>',
      termsParagraph5:
        "Wanswers.com is a platform for user-generated questions and answers. We do not guarantee the accuracy or reliability of the information provided by users. You use the site at your own risk, and Wanswers.com is not liable for any consequences resulting from the use of the site.",
      termsParagraph6:
        "Wanswers.com is not liable for any direct, indirect, incidental, or consequential damages resulting from your use of the website.",
      termsParagraph7:
        "These terms and conditions are governed by the laws of the European Union. Any disputes arising from the use of Wanswers.com shall be resolved through common dispute resolution practices, such as mediation or arbitration, before resorting to litigation.",
      termsParagraph8:
        'We reserve the right to change these terms at any time. Continued use of Wanswers.com after changes are made constitutes your acceptance of the updated terms. <p className="mt-5"> If you have any questions about these terms and conditions, please contact us at <a href="mailto: support@wanswers.com" className="text-lg">support@wanswers.com</a></p>',
      allRightsReserved: "All rights reserved.",
      privacyPageTitle: "Privacy Policy",
      privacyTitle0: "1. Information We Collect",
      privacyTitle1: "2. How We Use Your Information",
      privacyTitle2: "3. Data Sharing",
      privacyTitle3: "4. Data Security",
      privacyTitle4: "5. Data Retention",
      privacyTitle5: "6. User Rights",
      privacyTitle6: "7. Cookies and Tracking Technologies",
      privacyTitle7: "8. Children's Privacy",
      privacyTitle8: "9. Changes to This Privacy Policy",
      privacyTitle9: "10. Contact Information",
      privacyParagraph0:
        "Welcome to Wanswers.com. This Privacy Policy explains how we collect, use, and protect your information when you use our website. By using Wanswers.com, you agree to the terms outlined in this policy. If you do not agree, please do not use the site.",
      privacyParagraph1:
        'We collect the following types of information from our users:<ul className="ml-8 list-disc"><li><span className="font-bold">Email Address:</span> When you create an account or contact us.</li><li><span className="font-bold">Location Data:</span> To help tailor the site\'s functionality and analytics.</li><li><span className="font-bold">Cookies:</span> To manage sessions and track user interactions for analytics.</li></ul>',
      privacyParagraph2:
        'We use your information for the following purposes: <ul className="ml-8 list-disc"><li><span className="font-bold">Site Functionality:</span> To ensure the proper operation of the website, including user authentication and session management.</li><li><span className="font-bold">Analytics:</span> To analyze user behavior and improve the site\'s performance.</li></ul>',
      privacyParagraph3:
        "We do not share your personal information with third parties. If we need to work with third-party services for analytics or other functions, we will update this policy to reflect those changes.",
      privacyParagraph4:
        "We take your privacy seriously and use encryption to protect your data. Access to user information is restricted to authorized personnel only.",
      privacyParagraph5:
        "We retain your data for as long as necessary to fulfill the purposes for which it was collected. If you request deletion of your account or specific data, we will comply with the request, unless we have a legal obligation to retain it.",
      privacyParagraph6:
        'You have the following rights regarding your data:<ul className="ml-8 list-disc"><li><span className="font-bold">Correction:</span> You can update or correct your personal information in your account settings.</li><li><span className="font-bold">Deletion:</span> You can request the deletion of your account or specific personal data by contacting our support team. <p>To exercise these rights, you can manage your account settings or contact us at <a href="mailto: support@wanswers.com" className="text-lg">support@wanswers.com</a>.</p></li></ul>',
      privacyParagraph7:
        "We use cookies to manage user sessions and track interactions with the website for analytics purposes. You can adjust your browser settings to manage or block cookies, but this may affect your ability to use certain features on the website.",
      privacyParagraph8:
        "Wanswers.com is not intended for children under 13 years old. We do not knowingly collect personal information from children. If we become aware that a child under 13 has provided us with personal information, we will take steps to delete such information.",
      privacyParagraph9:
        "We reserve the right to update this Privacy Policy as needed. We encourage you to review this policy periodically for any changes. Continued use of Wanswers.com after changes are made constitutes your acceptance of the updated policy.",
      privacyParagraph10:
        'If you have any questions or concerns about this Privacy Policy, please contact us at <a href="mailto: support@wanswers.com" className="text-lg">support@wanswers.com</a>',

      noUsers: "No users yet",
      joinUs: "Join now to be the first!",
      allUsers: "All Users",
      userLocation: "User location",
      prefferedLang: "Preferred language",
      description: "Description",
      editProfile: "Edit profile",
      askedQuestions: "This user has inquired about some questions:",
      askedQuestions1: "Looks like",
      askedQuestions2: "hasn't asked any questions yet",
      givenAnswers1: "hasn't answered any questions yet",
      givenAnswers: "This user provided a few answers for next questions:",
      leftComments: "There are no comments from",
      leftComments2: "yet",
      noResultQTitle: "There is no question to show",
      noResultForQPageTitle: "There is no question with with a similar title",
      noResultTTitle: "There is no tag question to show",
      noResultQDescription:
        "Be the first to break the silence. 🚀 Ask question and kickstart the discussion. Your query could be the next big thing that others learn from. Get involved! 💡",
      moreQuestions: "More questions",
      allQuestions: "All questions",
      tagSearch: "Search tag questions",
      userSocialNetworks: "User Social Networks",
      name: "Name",
      country: "Country",
      city: "City",
      bio: "Bio",
      youtube: "Youtube link",
      linkedin: "Linkedin link",
      facebook: "Facebook link",
      instagram: "Instagram link",
      github: "GitHub link",
      twitter: "X link",
      save: "Save",
      saving: "Saving...",
      whereAreYouFrom: "Where are you from?",
      tellAboutYou: "Write a description about yourself",
      whichLanguage: "Which language do you prefer?",
      searchForAmazingMinds: "Search for amazing minds",
      searchForTags: "Search for tags",
      allTags: "All Tags",
      questionTitle: "Question Title",
      whatYourQuestion: "Start your question with 'What', 'How', 'Why' and so on",
      tip1: "Be specific and imagine you're asking a question to another person",
      tip2: "Detail explanation of your problem",
      tip3: "It would be really helpful if you could provide additional details, but it's completely optional 😉",
      tip4: "Type & then press",
      tip5: " Enter ↵ ",
      tip6: 'to add a tag. Add tags to describe what your question is about. You need to press enter to add a tag, or press button "Add".',
      addTags: "Add tags...",
      butonAdd: "Add",
      postQuestion: "Post Question",
      posting: "Posting...",
      saveChanges: "Save Changesя",
      updating: "Updating...",
      toastCreateQuestion: "Question posted successfully",
      toastUpdateQuestion: "Question updated successfully",
      writeYourAnswerHere: "Say something",
      addComment: "Add your comment",
      comment: "Comment",
      show: "Show",
      moreComments: "more comments",
      next: "Next",
      prev: "Prev",
      developedBy: "Developed by",
    },
    ru: {
      mainQuestiinHeader: "Все Вопросы",
      titleError:
        "Такой вопрос уже был задан на нашей платформе. Пожалуйста, поищите его на странице вопросов.",
      askQuestion: "Задать вопрос",
      searchQuestions: "Поиск по вопросам",
      tinyPlaceholder: "Опишите ваш вопрос (необязательно)",
      password: "Пароль",
      confirmPassword: "Подтвердите пароль",
      email: "Электронная почта",
      signInWelcomeTitle: "Войдите в свой аккаунт",
      passwordsDoNotMatch: "Пароли не совпадают",
      signUpWelcomeTitle: "Создай себе аккаунт",
      haveNoAccount: "Нет аккаунта?",
      haveAccount: "Уже есть аккаунт?",
      successSignIn: "Успешный вход!",
      successSignUp: "Аккаунт был создан успешно!",
      welcomeVariants: "Или продолжите с",
      asked: "задан",
      ago: "назад",
      week: "неделю",
      weeks: "недели",
      day: "день",
      days: "дней",
      hour: "час",
      hours: "часов",
      month: "месяц",
      months: "месяцев",
      minute: "минуту",
      minutes: "минут",
      second: "секунду",
      seconds: "секунд",
      noAnswer: "Ещё нет ответов",
      answer: "ответ",
      answers: "ответов",
      questions: "Вопросы",
      question: "Вопрос",
      questions2: "Вопросов",
      questions3: "вопрос",
      questions4: "вопросы",
      questions5: "вопросов",
      comments: "комментариев",
      comment1: "комментарий",
      page: "Страница",
      from: "из",
      users: "Пользователи",
      tags: "Тэги",
      profile: "Профиль",
      topQuestions: "Топ Вопросов",
      topTags: "Популярные Тэги",
      login: "Войти",
      signup: "Зарегистрироваться",
      aboutUsPageTitle: "О нас",
      aboutUsParagraph1:
        "Wanswers — это место, где каждый может задавать вопросы и получать на них полезные ответы.",
      aboutUsParagraph2:
        "Мы верим, что у каждого из нас есть знания и опыт, которыми можно поделиться. Задавая вопросы, мы учимся новому. ",
      aboutUsParagraph3:
        "Если вы студент, профессионал или просто любопытный человек, Wanswers — идеальное место для вас. Здесь вы сможете найти ответы на любые интересующие вас вопросы.",
      aboutUsParagraph4:
        "Наша команда состоит из людей, которых объединяет любовь к обучению и большим желанием внести позитивный вклад в общество. Среди наших специалистов есть эксперты в области образования, технологий и коммуникаций.",
      aboutUsParagraph5:
        "Мы видим, что есть большая потребность в платформе, где обычные люди могут задавать вопросы и получать ответы, не боясь осуждения. Именно поэтому мы создали и развиваем Wanswers — сайт, который поможет вам найти необходимую информацию. Уникальность Wanswers заключается в нашем внимании к качеству и сотрудничеству.",
      aboutUsParagraph6:
        "Одна из наших основных целей — дать пользователям возможность вести диалог друг с другом. Можно не только публиковать ответы, но и оставлять искренние и полезные комментарии, а также поддерживать конструктивную беседу.",
      aboutUsParagraph7:
        "Наши модераторы тщательно проверяют контент на достоверность, полезность и соответствие тематике сайта.",
      aboutUsParagraph8:
        "Если у вас есть какие-либо предложения или отзывы, мы всегда готовы их выслушать.",
      termsPageTitle: "Условия и Положения",
      termsTitle1: "1. Пользовательские аккаунты",
      termsTitle2: "2. Поведение пользователя",
      termsTitle3: "3. Владение контентом",
      termsTitle4: "4. Конфиденциальность и обработка данных",
      termsTitle5: "5. Отказ от ответственности",
      termsTitle6: "6. Ограничение ответственности",
      termsTitle7: "7. Законодательство и разрешение споров",
      termsTitle8: "8. Изменения в условиях",
      termsParagraph0:
        "Добро пожаловать на Wanswers.com. Используя наш вебсайт, вы соглашаетесь с этими условиями и положениями. Если вы не согласны, пожалуйста, не используйте вебсайт. Мы оставляем за собой право в любое время обновлять эти условия, и вам необходимо периодически их просматривать.",
      termsParagraph1:
        "Чтобы задавать вопросы или отвечать на них на Wanswers.com, вы должны создать аккаунт. Вы несете ответственность за конфиденциальность информации о своем аккаунте и за обеспечение точности вашей информации.",
      termsParagraph2:
        "Пользуясь Wanswers.com, вы соглашаетесь: <ul className='ml-8 list-disc'><li>Избегать спама, высказываний ненависти, домогательств или другого неуместного контента..</li><li>Воздерживаться от публикации материалов, которые нарушают авторские права без согласия автора.</li><li>Соблюдать любые дополнительные правила или руководства, которые могут быть введены.</li></ul><p className='mt-5'>Мы оставляем за собой право модерировать и удалять неуместный контент, а также принимать меры в отношении пользователей, нарушающих эти условия.</p>",
      termsParagraph3:
        "Публикуя вопросы или ответы на Wanswers.com, вы передаете нам права на контент. Это позволяет нам отображать, распространять и модифицировать контент по мере необходимости. Права на владение контентом не сохраняются за авторами.",
      termsParagraph4:
        'Мы обязуемся защищать вашу конфиденциальность. Wanswers.com собирает и использует ваши данные в соответствии с общепринятыми практиками конфиденциальности, включая:: <ul className="ml-8 list-disc"><li>Сбор пользовательских данных для функциональности и улучшения сайта</li> <li>Отказ от передачи ваших данных третьим лицам, за исключением случаев, предусмотренных законом.</li> <li>Безопасное хранение пользовательских данных для предотвращения несанкционированного доступа.</li> </ul> <p className="mt-5">Для получения более подробной информации обратитесь к нашей <a href="/privacy-policy">Политике конфиденциальности</a>.</p>',
      termsParagraph5:
        "Wanswers.com - это платформа для вопросов и ответов, созданных пользователями. Мы не гарантируем точность или надежность информации, предоставленной пользователями. Вы используете сайт на свой страх и риск, и Wanswers.com не несет ответственности за любые последствия использования сайта.",
      termsParagraph6:
        "Wanswers.com не несет ответственности за прямые, косвенные, случайные или последующие убытки, возникающие в результате вашего использования вебсайта.",
      termsParagraph7:
        "Эти условия и положения регулируются законами Европейского союза. Любые споры, возникающие из использования Wanswers.com, должны быть разрешены по общим практикам разрешения споров, таким как медиация или арбитраж, перед обращением в суд.",
      termsParagraph8:
        'Мы оставляем за собой право вносить изменения в эти условия в любое время. Продолжение использования Wanswers.com после внесения изменений означает ваше согласие с обновленными условиями. <p className="mt-5"> Если у вас есть какие-либо вопросы по поводу этих условий и положений, пожалуйста, свяжитесь с нами по адресу <a href="mailto: support@wanswers.com" className="text-lg">support@wanswers.com</a></p>',
      allRightsReserved: "Все права защищены.",
      privacyPageTitle: "Политика конфиденциальности",
      privacyTitle0: "1. Информация, которую мы собираем",
      privacyTitle1: "2. Как мы используем вашу информацию",
      privacyTitle2: "3. Обмен данными",
      privacyTitle3: "4. Безопасность данных",
      privacyTitle4: "5. Сохранение данных",
      privacyTitle5: "6. Права пользователей",
      privacyTitle6: "7. Cookies и технологии отслеживания",
      privacyTitle7: "8. Конфиденциальность детей",
      privacyTitle8: "9. Изменения в настоящей Политике конфиденциальности",
      privacyTitle9: "10. Контактная информация",
      privacyParagraph0:
        "Добро пожаловать на Wanswers.com. Настоящая Политика конфиденциальности объясняет, как мы собираем, используем и защищаем вашу информацию при использовании нашего вебсайта. Используя Wanswers.com, вы соглашаетесь с условиями, изложенными в этой политике. Если вы не согласны, пожалуйста, не используйте сайт.",
      privacyParagraph1:
        'Мы собираем следующие типы информации от наших пользователей:<ul className="ml-8 list-disc"><li><span className="font-bold">Адрес электронной почты:</span> для создании аккаунта или связи с нами.</li><li><span className="font-bold">Данные о местоположении:</span> для настройки функциональности сайта и аналитики.</li><li><span className="font-bold">Cookies:</span> для управления сеансами и отслеживания взаимодействия пользователей для аналитики.</li></ul>',
      privacyParagraph2:
        'Мы используем вашу информацию для следующих целей: <ul className="ml-8 list-disc"><li><span className="font-bold">Функциональность сайта:</span> для обеспечения правильной работы сайта, включая аутентификацию пользователей и управление сессиями.</li><li><span className="font-bold">Аналитика:</span> для анализа поведения пользователей и улучшения производительности сайта.</li></ul>',
      privacyParagraph3:
        "Мы не передаем вашу личную информацию третьим лицам. Если нам потребуется работа с услугами третьих сторон для аналитики или других функций, мы обновим данную политику, чтобы отразить эти изменения.",
      privacyParagraph4:
        "Мы серьезно относимся к вашей конфиденциальности и используем шифрование для защиты ваших данных. Доступ к информации пользователей разрешен только авторизованному персоналу.",
      privacyParagraph5:
        "Мы сохраняем ваши данные столько времени, сколько это необходимо для достижения целей, ради которых они были собраны. Если вы запросите удаление вашего аккаунта или определенных данных, мы удовлетворим ваш запрос, если у нас нет законного обязательства сохранить их.",
      privacyParagraph6:
        'У вас есть следующие права относительно ваших данных::<ul className="ml-8 list-disc"><li><span className="font-bold">Исправление:</span> вы можете обновить или исправить свою личную информацию в настройках вашего аккаунта.</li><li><span className="font-bold">Удаление:</span> вы можете запросить удаление вашего аккаунта или определенных личных данных, обратившись в нашу службу поддержки. <p>Чтобы воспользоваться этими правами, вы можете управлять настройками вашего аккаунта или связаться с нами по адресу <a href="mailto: support@wanswers.com" className="text-lg">support@wanswers.com</a>.</p></li></ul>',
      privacyParagraph7:
        "Мы используем cookies для управления сеансами пользователей и отслеживания взаимодействия с вебсайтом в целях аналитики. Вы можете настроить параметры вашего браузера для управления или блокировки куки, однако это может повлиять на вашу способность использовать определенные функции на сайте.",
      privacyParagraph8:
        "Wanswers.com не предназначен для детей младше 13 лет. Мы не собираем личную информацию о детях. Если мы узнаем, что ребенок младше 13 лет предоставил нам личную информацию, мы примем меры для удаления такой информации.",
      privacyParagraph9:
        "Мы оставляем за собой право вносить изменения в настоящую Политику конфиденциальности по мере необходимости. Мы рекомендуем вам периодически просматривать эту политику для получения информации о любых изменениях. Продолжение использования Wanswers.com после внесения изменений означает ваше согласие с обновленной политикой.",
      privacyParagraph10:
        'Если у вас есть какие-либо вопросы или замечания по поводу настоящей Политики конфиденциальности, пожалуйста, свяжитесь с нами по адресу <a href="mailto: support@wanswers.com" className="text-lg">support@wanswers.com</a>',
      noUsers: "Ещё нет пользователей",
      joinUs: "Присоединяйтесь к нам, чтобы быть первым!",
      allUsers: "Все пользователи",
      userLocation: "Локация пользователя",
      prefferedLang: "Предпочитаемый язык",
      description: "Описание",
      editProfile: "Редактировать профайл",
      askedQuestions: "Этот пользователь задал несколько вопросов:",
      askedQuestions1: "Похоже, что",
      askedQuestions2: "не задавал ещё вопросов",
      givenAnswers1: "не давал ещё ответов на вопросы",
      givenAnswers: "Этот пользователь предоставил несколько ответов на следующие вопросы:",
      leftComments: "Комментариев от",
      leftComments2: "ещё нет",
      noResultQTitle: "Нет никаких вопросов, которые нужно было бы показать",
      noResultForQPageTitle: "Не удалось найти ни одного вопроса с подобным описанием",
      noResultTTitle: "Нет никаких тэгированных вопросов, которые нужно было бы показать",
      noResultQDescription:
        "Будьте первым, кто нарушит тишину. 🚀 Задавайте вопросы и начинайте обсуждение. Ваш запрос может стать следующим важным уроком для других. Участвуйте! 💡",
      moreQuestions: "Больше вопросов",
      allQuestions: "Все вопросы",
      tagSearch: "Поиск по тэгированым вопросам",
      userSocialNetworks: "Социальные сети пользователя",
      name: "Имя",
      country: "Страна",
      city: "Город",
      bio: "Биография",
      youtube: "Youtube ссылка",
      linkedin: "Linkedin ссылка",
      facebook: "Facebook ссылка",
      instagram: "Instagram ссылка",
      github: "GitHub ссылка",
      twitter: "X ссылка",
      save: "Сохранить",
      saving: "Сохранение...",
      whereAreYouFrom: "Откуда Вы?",
      tellAboutYou: "Пожалуйста, расскажите о себе.",
      whichLanguage: "Какой язык Вы предпочитаете?",
      searchForAmazingMinds: "Ищите удивительные умы",
      searchForTags: "Поиск по тэгам",
      allTags: "Все Тэги",
      questionTitle: "Вопрос:",
      whatYourQuestion:
        'Начните свой вопрос с слова "Что", "Какой", "Почему" или подобного слова-вопроса',
      tip1: "Будьте конкретны и представьте, что вы задаете вопрос другому человеку",
      tip2: "Подробное объяснение вашей проблемы",
      tip3: "Было бы очень полезно, если бы вы предоставили дополнительную информацию, но это совершенно необязательно 😉",
      tip4: "Введите и затем нажмите",
      tip5: " Enter ↵ ",
      tip6: 'Чтобы добавить тег. Добавьте теги, описывающие суть вашего вопроса. Для добавления тега вам нужно нажать клавишу Enter ↵ или кнопку "Добавить"',
      butonAdd: "Добавить",
      addTags: "Добавить тэги...",
      postQuestion: "Опубликовать Вопрос",
      posting: "Публикация...",
      saveChanges: "Сохранить Изменения",
      updating: "Обновление...",
      toastCreateQuestion: "Вопрос опубликован успешно!",
      toastUpdateQuestion: "Вопрос успешно обновлён!",
      writeYourAnswerHere: "Напишите что-нибудь",
      addComment: "Добавить комментарий",
      comment: "Комментарий",
      show: "Показать ещё",
      moreComments: "комментариев",
      next: "Следующий",
      prev: "Предыдущий",
      developedBy: "Разработано",
    },
  };
}
